environment:

  matrix:

    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35-x64"


install:
  - "%PYTHON%/Scripts/pip.exe install virtualenv"
  - "%PYTHON%/Scripts/pip.exe install git+git://github.com/spacetelescope/asv.git@master"
  - git clone https://github.com/MSeifert04/iteration_utilities.git
  - "%PYTHON%/Scripts/asv.exe machine --machine AppVeyor --os AppVeyor --arch unknown --cpu unknown --ram unknown"


build: off

test_script:
  - "%PYTHON%/Scripts/asv.exe run --machine AppVeyor"

artifacts:
  - path: .asv\results\
